name: Clean

on:
  workflow_run:
    workflows: ["Build-6.6", "Build-6.18", "Build-6.6_ax6000_immortalwrt_237_golang_msd_lite_110m"]
    types:
      - completed
  workflow_dispatch:
  
permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
    - name: Delete releases and workflows runs
      uses: ophub/delete-releases-workflows@main
      with:
        delete_releases: true
        releases_keep_latest: 5
        delete_workflows: true
        workflows_keep_day: 30
        gh_token: ${{ secrets.GITHUB_TOKEN }}
